# Generated by Django 4.1.3 on 2022-11-02 10:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('genre', models.CharField(choices=[('FPS', 'First-Person Shooter'), ('S', 'Strategie'), ('A', 'Adventure'), ('MOBA', 'Multiplayer Online Battle Arena'), ('RPG', 'Rollenspiel'), ('R', 'Rätsel'), ('Sp', 'Sport'), ('TPS', 'Third-Person Shooter'), ('JnR', 'Jump and Run')], max_length=4)),
                ('fsk', models.IntegerField(choices=[(0, 'ab 0'), (6, 'ab 6'), (12, 'ab 12'), (16, 'ab 16'), (18, 'ab 18')])),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VideoGame',
                'verbose_name_plural': 'VideoGames',
            },
        ),
    ]
