# Generated by Django 4.1.3 on 2022-11-16 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Videogames', '0002_vote_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='videogame',
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Videogames.comment'),
            preserve_default=False,
        ),
    ]
