# Generated by Django 4.1.4 on 2023-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='image',
            field=models.FileField(upload_to='profile_images/'),
        ),
    ]
