# Generated by Django 4.1.4 on 2023-01-09 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0002_alter_defaultuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='date_of_brith',
            field=models.DateField(default=datetime.date(2003, 1, 9)),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='type',
            field=models.CharField(choices=[('SU', 'superuser'), ('CS', 'customer service'), ('CU', 'customer')], default='CU', max_length=2),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
