# Generated by Django 4.1.3 on 2022-12-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_alter_movie_image_alter_movie_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('H', 'Horror'), ('F', 'Familienfilm'), ('A', 'Action'), ('S', 'Superhelden')], default='H', max_length=1),
            preserve_default=False,
        ),
    ]
