# Generated by Django 4.1.3 on 2023-01-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_alter_movie_image_alter_movie_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='deleted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='reported',
            field=models.BooleanField(),
        ),
    ]
