# Generated by Django 4.1.3 on 2023-01-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_alter_productreview_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(blank=True, upload_to='movies/images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pdf',
            field=models.FileField(blank=True, upload_to='movies/pdf/'),
        ),
    ]
