# Generated by Django 4.1.3 on 2023-01-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0008_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
